version: '3.1'
services:
  build-backend:
    build:
      context: ./oauth2-pkce
      dockerfile: build.Dockerfile
    image: local/build__oauth2_backend:latest
    volumes:
      - ./oauth2-pkce:/opt/src
      - ./.docker-build/.m2:/root/.m2
  build-frontend:
    image: adorsys/ci-build:latest
    volumes:
      - ./angular-oauth2:/opt/src
    working_dir: /opt/src
    entrypoint: ""
    command:
      - /opt/src/docker/compile/build.cmd.bash
