version: '3.1'
services:
  keycloak:
    image: "jboss/keycloak:3.2.1.Final"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    ports:
    - "8080:8080"
    - "8787:8787"
    volumes:
    - "./.docker/keycloak/data:/opt/jboss/keycloak/standalone/data"
    networks:
    - my_network
    command:
    - "-b"
    - "0.0.0.0"
    - "--debug"
  post_process:
    image: adorsys/keycloak-config-cli:v0.2.2
    depends_on:
    - keycloak
    networks:
    - my_network
    volumes:
    - ./keycloak-config:/opt/keycloak-config-cli/configs
    environment:
    - KEYCLOAK_URL=http://keycloak:8080/auth
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin123
networks:
  my_network:
