server:
  port: 8888

pkce:
  client-id: moped-client
  client-secret: 939d28bd-8d06-4cd3-8324-10b4c7b12852
  access-token-uri: http://localhost:8080/auth/realms/moped/protocol/openid-connect/token
  user-authorization-uri: http://localhost:8080/auth/realms/moped/protocol/openid-connect/auth
  user-info-uri: http://localhost:8080/auth/realms/moped/protocol/openid-connect/userinfo
  logout-uri: http://localhost:8080/auth/realms/moped/protocol/openid-connect/logout
  redirect-uri: http://localhost/token
  user-agent-auto-protected-pages: /swagger-ui.html,/user,/me
  response-type: code

sts:
  authservers:
  - name: local keycloak
    iss-url: http://localhost:8080/auth/realms/moped
    jwks-url: http://localhost:8080/auth/realms/moped/protocol/openid-connect/certs
